[build]
  publish = "web"
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

# API routes go to Netlify Functions
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# SPA fallback: all other routes serve index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
