[build]
  publish = "web"
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

# 1) API 路由 → Functions
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# 2) SPA 路由 → index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
